### ISSUE TITLE
Include instances for `vector` and `scientific`

### ISSUE THREAD

**Issue by phadej** [aslatter/qc-instances#14]
They seem to be in platform nowadays, so they fall under:
> The goal is to supply QuickCheck instances for types provided by the Haskell Platform.

https://www.haskell.org/platform/contents.html

I can make a PR if the inclusion is ok?

**Comment by aslatter** [comment]
Yeah, that seems fine. Sorry for not noticing the issue for so long!

**Comment by seagreen** [comment]
I would also be interested in this.

**Comment by phadej** [comment]
made a PR

**Comment by aslatter** [comment]
Fixed in 6e37d1b9a655125cabcb9034492831c26a29e0b5.
