### ISSUE TITLE
Add OverlappingInstances ?

### ISSUE THREAD

**Issue by joe9** [aslatter/qc-instances#29]
Hello,

Thanks for sharing the module.

It is very useful but I find that I need different instances for some types.

I am wondering if you could add OverlappingInstances Pragma to allow users to override the instance, when the need arises. It is a pita to create a newtype just to override the Arbitrary instance.

Thanks
Joe

**Comment by joe9** [comment]
From http://book.realworldhaskell.org/read/using-typeclasses.html#id608052

When to use the OverlappingInstances extension

Here's an important point: GHC treats OverlappingInstances as affecting the declaration of an instance, not a location where we use the instance. In other words, when we define an instance that we wish to allow to overlap with another instance, we must enable the extension for the module that contains the definition. When it compiles the module, GHC will record that instance as “can be overlapped with other instances”.

Once we import this module and use the instance, we won't need to enable OverlappingInstances in the importing module: GHC will already know that the instance was marked as “okay to overlap” when it was defined.

This behaviour is useful when we are writing a library: we can choose to create overlappable instances, but users of our library do not need to enable any special language extensions.

**Comment by phadej** [comment]
@joe9 in recent GHC (starting from 7.10.3, IIRC) you can write

```
instance {-# OVERLAPPING #-} Arbitrary (Vector Int) where
   ...
```

(out of curiosity, what instances you want to overlap?) 

And to be sure: we won't make any instance overlappable with only weak reasons. They introduce quite a lot of headaches.
